In [1]:
import numpy as np

In [2]:
def compute_mean_and_variance(feature_vector):
    return np.mean(feature_vector), np.var(feature_vector)
N=5
feature_vector = np.random.rand(N)  
mean, variance = compute_mean_and_variance(feature_vector)
print("Feature vector:", feature_vector)
print("Mean:", mean)
print("Variance:", variance)

Feature vector: [0.70134782 0.98855317 0.21047567 0.04677694 0.30746627]
Mean: 0.45092397315192556
Variance: 0.11869751428660232


In [3]:
import numpy as np

In [4]:
def compute_covariance(vector1, vector2):
    return np.cov(vector1, vector2)[0,1]
m=3
vector1 = np.random.rand(m)
vector2 = np.random.rand(m)
covariance = compute_covariance(vector1, vector2)
print("Vector 1:", vector1)
print("Vector 2:", vector2)
print("Covariance:", covariance)

Vector 1: [0.34501265 0.05593825 0.309325  ]
Vector 2: [0.64281373 0.91411988 0.37670018]
Covariance: -0.034184288025247964


In [5]:
def compute_correlation(vector1, vector2):
    return np.corrcoef(vector1, vector2)[0,1]
m=3
vector1 = np.random.rand(m)
vector2 = np.random.rand(m)
correlation = compute_correlation(vector1, vector2)
print("Vector 1:", vector1)
print("Vector 2:", vector2)
print("Correlation:", correlation)

Vector 1: [0.67055149 0.29838199 0.07954374]
Vector 2: [0.83952826 0.09701413 0.25708224]
Correlation: 0.8358106350750539


In [1]:
import numpy as np
def compute_covariance_matrix(matrix):
    covariance_matrix = np.cov(matrix)
    return covariance_matrix

def compute_correlation_matrix(matrix):
    correlation_matrix = np.corrcoef(matrix)
    return correlation_matrix

def main():
    feature_matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
    covariance_matrix = compute_covariance_matrix(feature_matrix)
    correlation_matrix = compute_correlation_matrix(feature_matrix)

    print("Feature Matrix:")
    print(feature_matrix)

    print("\nCovariance Matrix:")
    print(covariance_matrix)

    print("\nCorrelation Matrix:")
    print(correlation_matrix)

if __name__ == "__main__":
    main()


Feature Matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Covariance Matrix:
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

Correlation Matrix:
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
