### Create a vector (array) of 1XN dimension representing N-dimensional feature vector of a sample. Write a program to compute the mean and variance of the elements present in the array.


In [1]:
import numpy as np

In [10]:
def compute_mean_and_variance(feature_vector):
    return np.mean(feature_vector), np.var(feature_vector)

In [11]:
N=5
feature_vector = np.random.rand(N)  
mean, variance = compute_mean_and_variance(feature_vector)

In [12]:
print("Feature vector:", feature_vector)
print("Mean:", mean)
print("Variance:", variance)

Feature vector: [0.29678345 0.60019067 0.00239229 0.67997175 0.92140793]
Mean: 0.5001492181559212
Variance: 0.10178458514709865


### 2. Create two vectors each of dimension 1XM each representing N-dimensional feature vector of a sample. Write a program to compute the Covariance between them.

In [17]:
import numpy as np

In [14]:
def compute_covariance(vector1, vector2):
    return np.cov(vector1, vector2)[0,1]

In [15]:
m=3
vector1 = np.random.rand(m)
vector2 = np.random.rand(m)
covariance = compute_covariance(vector1, vector2)

In [16]:
print("Vector 1:", vector1)
print("Vector 2:", vector2)
print("Covariance:", covariance)

Vector 1: [0.93804597 0.79462215 0.70499864]
Vector 2: [0.66170836 0.85386627 0.26299886]
Covariance: 0.019718961797140777


### Create two vectors each of dimension 1XN. Write a program to compute the Correlation between them.



In [18]:
import numpy as np


In [23]:
def compute_correlation(vector1, vector2):
    return np.corrcoef(vector1, vector2)[0,1]

In [24]:
m=3
vector1 = np.random.rand(m)
vector2 = np.random.rand(m)
correlation = compute_correlation(vector1, vector2)

In [25]:
print("Vector 1:", vector1)
print("Vector 2:", vector2)
print("Correlation:", correlation)

Vector 1: [0.31421174 0.78612321 0.74756991]
Vector 2: [0.97917845 0.50116012 0.27866169]
Correlation: -0.925035028309979


### Create a Matrix of MXN dimension representing the M-dimensional feature vector for N number of samples i. e (i,j)th entry of the matrix represents the ith feature of jth sample. Write a program to compute the covariance matrix and correlation matrix.

In [26]:
import numpy as np

In [29]:
def compute_correlation_matrix(feature_vector):
    correlation_matrix = np.corrcoef(feature_matrix)
    return correlation_matrix

In [30]:
feature_matrix = np.array([[1, 2, 3],
                            [4, 5, 6],
                            [7, 8, 9]])

cov_matrix = compute_covariance_matrix(feature_matrix)
correlation_matrix = compute_correlation_matrix(feature_matrix)

In [31]:
print("Covariance Matrix:")
print(cov_matrix)

print("\nCorrelation Matrix:")
print(correlation_matrix)

Covariance Matrix:
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

Correlation Matrix:
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
